### ISSUE TITLE
Fails when running in NodeJS.

### ISSUE THREAD

**Issue by AlbertWillemsen-Centric** [lifaon74/url-polyfill#1]
Hi,

I am trying to use this api in NodeJS.
Fails because window is undefined inside NodeJS.
Should be able to attach this api to global.
Suggest removing window check.

Using nasty workaround to get it working:
```
const window: any = (global as any).window = global;
window.location = {};
```

With Kind Regards,
Albert Willemsen

**Comment by lifaon74** [comment]
In fact, it can't work in nodejs because it requires DOM. The polyfill is intended for browser with minimal size, else the entire lib should be re-writen from scratch, meaning by the way a far bigger size.

I was thinking about a `url-node.js` dedicated to node. Nothing is planed yet, but it could be done later if I have time.

**Comment by AlbertWillemsen-Centric** [comment]
With a small change it would become compatible with NodeJS.
Willing to do a pull request.

**Comment by lifaon74** [comment]
I'm open to pull request.

**Comment by AlbertWillemsen-Centric** [comment]
How do i run your mocha tests?
Do i need to install some prerequisites?

**Comment by lifaon74** [comment]
https://github.com/lifaon74/url-polyfill/tree/master/tests

You'll need a test server with selenium (you can install one locally), install all dependencies (including dev), edit the config file, start the local content server and finally run test. If you don't find how to do it, don't bother, I'll do myself ;)
