### ISSUE TITLE
Inconsistent when double '?' in string

### ISSUE THREAD

**Issue by outdooricon** [lifaon74/url-polyfill#13]
In Chrome 63, If I run:

```javascript
const test1 = new URLSearchParams('?a=1?b=2&c=3');
test1.get('a');
```
then I get `1?b=2`

With this polyfill, I get `1?b`.

Url-search-params-polyfill also mimicks the Chrome behavior.

**Comment by lifaon74** [comment]
Well I see many peole tricking the polyfill by passing strange values. Browsers and WHATWG specs handle a huge amount a usecases (like special chars, unicodes, types different than string, etc...). All of theses checks (to handle properly all usecases) whould require a far bigger filesize which is the oposite of the intention... It's far easier for the developper to provide correct values instead of reling on brower/lib to patch them... Here you could simply use encodeURIComponent and get a proper url.

**Comment by lifaon74** [comment]
I wrote a full WHATWG implementation of the URL and URLSearchParams + other utils [url.zip](https://github.com/lifaon74/url-polyfill/files/1572997/url.zip)

The whole lib is around 277ko, works in a browser as well as nodejs. You can `require()` it or use bundle.URL or whaterver in the browser. I built it for es6, you can transpile it with babel for example.

```js
const test1 = new bundle.URLSearchParams('?a=1?b=2&c=3');
test1.get('a');
```

**Comment by outdooricon** [comment]
Thanks for the reply! Unfortunately, I'm reacting to bad urls' that have already been spread around, so I am in need of a consistent URLSearchParams experience as I'm handling that malform of the double `?`. It's fascinating to hear your perspective though and I completely understand your position of not being able to support all of the use cases. For me, It just means I'll need to rely on multiple URL polyfills for our use case. Thanks for making this great lib!
