### ISSUE TITLE
url-polyfill is loaded in Safari when not required

### ISSUE THREAD

**Issue by nekodex** [lifaon74/url-polyfill#14]
Seems to be because Safari escapes the pathname set by [url-polyfill.js#L173](https://github.com/lifaon74/url-polyfill/blob/5a0e96d78afb473333a427c4b56c8426dcd7d5eb/url-polyfill.js#L173), causing the comparison `(u.href === 'http://a/c%20d')` to return false:

![](https://puu.sh/z43km/32b55be269.png)

**Comment by supperchong** [comment]
I find the same problem.When I use [url-polyfill](https://github.com/lifaon74/url-polyfill/) and [pdfjs-dist](https://github.com/mozilla/pdfjs-dist) in my web,the url-polyfill will lose efficacy. Because pdf-dist use this code to check if URL is valid.
`         if (typeof URL === 'function' && _typeof(URL.prototype) === 'object' && 'origin' in URL.prototype) {
           var u = new URL('b', 'http://a');
        u.pathname = 'c%20d';
        hasWorkingUrl = u.href === 'http://a/c%20d';
      }`
But in safari,
` u.href==='http://a/c%2520d'`
And then the [pdfjs-dist](https://github.com/mozilla/pdfjs-dist) will rewrite URL.But the module doesn't achieve the searchParams method.fortunately the [pdfjs-dist](https://github.com/mozilla/pdfjs-dist) have  [Stop exposing the `URL` polyfill in the global scope](https://github.com/mozilla/pdf.js/commit/a9ce4e8417c379e4a1b580982502b73c9248f6a1).
 
More over ,If this is a bug ? [url-polyfill](https://github.com/lifaon74/url-polyfill) use this code to check URL is supported.But after execute the module .The check is false also in safari.
`var checkIfURLIsSupported = function() {
    try {
      var u = new URL('b', 'http://a');
      u.pathname = 'c%20d';
      return (u.href === 'http://a/c%20d') && u.searchParams;
    } catch(e) {
      return false;
    }
  };`

**Comment by lifaon74** [comment]
I don't have Safari on the hand. Could you fix it on your side, run the tests and create a pull request please ?

**Comment by moshest** [comment]
Currently looks like everything works fine (Safari 12.1.1):

<img width="761" alt="Screen Shot 2019-07-14 at 19 10 51" src="https://user-images.githubusercontent.com/534911/61186210-52a88c80-a66b-11e9-8179-e40706e920be.png">

**Comment by janicklas-ralph** [comment]
This is still an issue in Safari 10. Any idea what should be the fix?

**Comment by lifaon74** [comment]
@janicklas-ralph I dont have any Safari on the hand, could you please fork the project, fix the bug, and then do a pull request ?

**Comment by lifaon74** [comment]
Ok, version 1.1.8 released. Tell if everything is OK
