### ISSUE TITLE
Missing URLSearchParams#toString in url.ts and url.js

### ISSUE THREAD

**Issue by venkatkarun** [lifaon74/url-polyfill#6]
First of all, thank you for crafting a concise and excellent library. Our product runs into native code barfing with `new URL` in mobile Safari on iOS and I played around with your standalone classes and found them to be a perfect fit. Wondering if you have a public release planned with these classes soon.  

```js  
const url = new URL('http://echo/')
url.searchParams.set('qux', 'baz')
console.log(url.toString())

....
http://echo/?[object Object]
```

FWIW, was able to resolve things trivially with the following port from url-polyfill.js:

```js 
URLSearchParams.prototype.toString = function () { 
  var pairs = []; 
  this.forEach(function (value, name) { 
    pairs.push(encodeURIComponent(name) + '=' + encodeURIComponent(value)); 
  }); 
  return pairs.join('&'); 
}; 
```

```ts
toString() {
  const pairs = [];
  this.forEach(function (value, name) {
    pairs.push(encodeURIComponent(name) + '=' + encodeURIComponent(value));
  });
  return pairs.join('&');
}
```

**Comment by lifaon74** [comment]
Well, in fact you should not really use url.js because it was more an experimentation than a real polyfill. It's a real lightweight and incomplete implementation of URL and will only work for well formed http and https URL (blob, file not supported, unicode characters not supported, etc...). I created it as a last option if the url-polyfill.js is not working for you (like on nodejs or ie 9 & -).

So I added the method toString, thanks to you.

I'm currently working on the full URL implementation for nodejs < 8 but it won't be released until some time.
